"""
Strategy Engine - Rule-based trading strategies
IMPORTANT: Rule-based first, AI only filters/ranks
"""
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
import pandas as pd
from loguru import logger

from configs.settings import settings


class SignalType(Enum):
    """Types of trading signals"""
    LONG = "long"
    SHORT = "short"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    HOLD = "hold"


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    symbol: str
    strategy: str
    signal_type: SignalType
    entry_price: float
    stop_loss: float
    target_price: float
    confidence: float  # 0-1
    timeframe: str
    timestamp: datetime
    metadata: dict
    
    def to_dict(self) -> dict:
        return {
            'symbol': self.symbol,
            'strategy': self.strategy,
            'signal_type': self.signal_type.value,
            'entry_price': self.entry_price,
            'stop_loss': self.stop_loss,
            'target_price': self.target_price,
            'confidence': self.confidence,
            'timeframe': self.timeframe,
            'timestamp': self.timestamp.isoformat(),
            'metadata': self.metadata
        }


class EMATrendStrategy:
    """
    EMA Trend Following Strategy
    
    BUY CONDITIONS:
    - EMA20 > EMA50
    - RSI > 60
    - Volume Spike > 1.5x average
    - Price above VWAP
    - Regime == BULL
    
    SELL CONDITIONS:
    - EMA20 < EMA50
    - RSI < 40
    - Price below VWAP
    - Regime == BEAR
    """
    
    def __init__(self):
        self.name = "ema_trend"
        logger.info("EMATrendStrategy initialized")
    
    def generate_signal(
        self,
        symbol: str,
        candles: pd.DataFrame,
        regime: str,
        current_price: float
    ) -> Optional[Signal]:
        """Generate trading signal based on EMA crossover logic"""
        
        if len(candles) < 50:
            logger.debug(f"Insufficient data for {symbol}: {len(candles)} candles")
            return None
        
        # Calculate indicators
        ema_20 = candles['close'].ewm(span=settings.EMA_FAST, adjust=False).mean()
        ema_50 = candles['close'].ewm(span=settings.EMA_SLOW, adjust=False).mean()
        
        # RSI calculation (simplified)
        delta = candles['close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=settings.RSI_PERIOD).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=settings.RSI_PERIOD).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        
        # Volume average
        avg_volume = candles['volume'].rolling(window=20).mean()
        current_volume = candles['volume'].iloc[-1]
        volume_ratio = current_volume / avg_volume.iloc[-1] if avg_volume.iloc[-1] > 0 else 0
        
        # VWAP (simplified - using typical price)
        typical_price = (candles['high'] + candles['low'] + candles['close']) / 3
        vwap = (typical_price * candles['volume']).rolling(window=settings.VWAP_PERIOD).mean() / \
               candles['volume'].rolling(window=settings.VWAP_PERIOD).mean()
        
        # Get latest values
        latest_ema_20 = ema_20.iloc[-1]
        latest_ema_50 = ema_50.iloc[-1]
        latest_rsi = rsi.iloc[-1]
        latest_vwap = vwap.iloc[-1]
        
        # Check for LONG signal
        if (latest_ema_20 > latest_ema_50 and 
            latest_rsi > 60 and 
            volume_ratio > 1.5 and 
            current_price > latest_vwap and
            regime in ['BULL', 'HIGH_VOL']):
            
            # Calculate stop loss and target
            atr = self._calculate_atr(candles)
            stop_loss = current_price - (2 * atr)
            target_price = current_price + (3 * atr)  # 1:3 risk-reward
            
            signal = Signal(
                symbol=symbol,
                strategy=self.name,
                signal_type=SignalType.LONG,
                entry_price=current_price,
                stop_loss=stop_loss,
                target_price=target_price,
                confidence=min(0.9, 0.5 + (volume_ratio - 1.5) * 0.1 + (latest_rsi - 60) * 0.01),
                timeframe='5m',
                timestamp=datetime.utcnow(),
                metadata={
                    'ema_20': latest_ema_20,
                    'ema_50': latest_ema_50,
                    'rsi': latest_rsi,
                    'volume_ratio': volume_ratio,
                    'vwap': latest_vwap,
                    'regime': regime,
                    'atr': atr
                }
            )
            
            logger.info(f"LONG signal for {symbol}: entry={current_price:.2f}, sl={stop_loss:.2f}")
            return signal
        
        # Check for SHORT signal
        elif (latest_ema_20 < latest_ema_50 and 
              latest_rsi < 40 and 
              current_price < latest_vwap and
              regime in ['BEAR', 'HIGH_VOL']):
            
            # Calculate stop loss and target
            atr = self._calculate_atr(candles)
            stop_loss = current_price + (2 * atr)
            target_price = current_price - (3 * atr)  # 1:3 risk-reward
            
            signal = Signal(
                symbol=symbol,
                strategy=self.name,
                signal_type=SignalType.SHORT,
                entry_price=current_price,
                stop_loss=stop_loss,
                target_price=target_price,
                confidence=min(0.9, 0.5 + (40 - latest_rsi) * 0.01),
                timeframe='5m',
                timestamp=datetime.utcnow(),
                metadata={
                    'ema_20': latest_ema_20,
                    'ema_50': latest_ema_50,
                    'rsi': latest_rsi,
                    'vwap': latest_vwap,
                    'regime': regime,
                    'atr': atr
                }
            )
            
            logger.info(f"SHORT signal for {symbol}: entry={current_price:.2f}, sl={stop_loss:.2f}")
            return signal
        
        return None
    
    def _calculate_atr(self, candles: pd.DataFrame, period: int = 14) -> float:
        """Calculate Average True Range"""
        high = candles['high']
        low = candles['low']
        close = candles['close'].shift(1)
        
        tr1 = high - low
        tr2 = abs(high - close)
        tr3 = abs(low - close)
        
        true_range = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = true_range.rolling(window=period).mean()
        
        return atr.iloc[-1] if not pd.isna(atr.iloc[-1]) else 0.0


class VWAPMeanReversionStrategy:
    """
    VWAP Mean Reversion Strategy
    
    Logic:
    - If price far above VWAP and RSI > 75: SHORT
    - If price far below VWAP and RSI < 25: LONG
    """
    
    def __init__(self):
        self.name = "vwap_mean_reversion"
        logger.info("VWAPMeanReversionStrategy initialized")
    
    def generate_signal(
        self,
        symbol: str,
        candles: pd.DataFrame,
        regime: str,
        current_price: float
    ) -> Optional[Signal]:
        """Generate mean reversion signal"""
        
        if len(candles) < 20:
            return None
        
        # Calculate VWAP
        typical_price = (candles['high'] + candles['low'] + candles['close']) / 3
        vwap = (typical_price * candles['volume']).rolling(window=settings.VWAP_PERIOD).mean() / \
               candles['volume'].rolling(window=settings.VWAP_PERIOD).mean()
        
        # RSI
        delta = candles['close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=settings.RSI_PERIOD).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=settings.RSI_PERIOD).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        
        latest_vwap = vwap.iloc[-1]
        latest_rsi = rsi.iloc[-1]
        
        # Calculate distance from VWAP in percentage
        vwap_distance_pct = ((current_price - latest_vwap) / latest_vwap) * 100
        
        # SHORT signal: price far above VWAP + overbought RSI
        if vwap_distance_pct > 2.0 and latest_rsi > 75 and regime != 'BULL':
            atr = self._calculate_atr(candles)
            stop_loss = current_price + (2 * atr)
            target_price = latest_vwap  # Target is mean reversion to VWAP
            
            signal = Signal(
                symbol=symbol,
                strategy=self.name,
                signal_type=SignalType.SHORT,
                entry_price=current_price,
                stop_loss=stop_loss,
                target_price=target_price,
                confidence=min(0.85, 0.5 + (vwap_distance_pct - 2) * 0.1 + (latest_rsi - 75) * 0.01),
                timeframe='5m',
                timestamp=datetime.utcnow(),
                metadata={
                    'vwap': latest_vwap,
                    'rsi': latest_rsi,
                    'vwap_distance_pct': vwap_distance_pct,
                    'regime': regime
                }
            )
            
            logger.info(f"SHORT signal (mean reversion) for {symbol}")
            return signal
        
        # LONG signal: price far below VWAP + oversold RSI
        elif vwap_distance_pct < -2.0 and latest_rsi < 25 and regime != 'BEAR':
            atr = self._calculate_atr(candles)
            stop_loss = current_price - (2 * atr)
            target_price = latest_vwap  # Target is mean reversion to VWAP
            
            signal = Signal(
                symbol=symbol,
                strategy=self.name,
                signal_type=SignalType.LONG,
                entry_price=current_price,
                stop_loss=stop_loss,
                target_price=target_price,
                confidence=min(0.85, 0.5 + abs(vwap_distance_pct + 2) * 0.1 + (25 - latest_rsi) * 0.01),
                timeframe='5m',
                timestamp=datetime.utcnow(),
                metadata={
                    'vwap': latest_vwap,
                    'rsi': latest_rsi,
                    'vwap_distance_pct': vwap_distance_pct,
                    'regime': regime
                }
            )
            
            logger.info(f"LONG signal (mean reversion) for {symbol}")
            return signal
        
        return None
    
    def _calculate_atr(self, candles: pd.DataFrame, period: int = 14) -> float:
        """Calculate Average True Range"""
        high = candles['high']
        low = candles['low']
        close = candles['close'].shift(1)
        
        tr1 = high - low
        tr2 = abs(high - close)
        tr3 = abs(low - close)
        
        true_range = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = true_range.rolling(window=period).mean()
        
        return atr.iloc[-1] if not pd.isna(atr.iloc[-1]) else 0.0


class MomentumBreakoutStrategy:
    """
    Momentum Breakout Strategy
    
    Logic:
    - Price breaks previous high
    - Volume > 2x average
    - OI change positive (for futures/options)
    - Market breadth positive
    """
    
    def __init__(self):
        self.name = "momentum_breakout"
        logger.info("MomentumBreakoutStrategy initialized")
    
    def generate_signal(
        self,
        symbol: str,
        candles: pd.DataFrame,
        regime: str,
        current_price: float,
        oi_change: float = 0,
        market_breadth: float = 0
    ) -> Optional[Signal]:
        """Generate momentum breakout signal"""
        
        if len(candles) < 20:
            return None
        
        # Calculate 20-period high
        period_high = candles['high'].rolling(window=20).max()
        previous_high = period_high.iloc[-2] if len(period_high) > 1 else period_high.iloc[-1]
        
        # Volume analysis
        avg_volume = candles['volume'].rolling(window=20).mean()
        current_volume = candles['volume'].iloc[-1]
        volume_ratio = current_volume / avg_volume.iloc[-1] if avg_volume.iloc[-1] > 0 else 0
        
        # Check for breakout
        breakout_detected = current_price > previous_high
        
        if (breakout_detected and 
            volume_ratio > 2.0 and 
            oi_change > 0 and 
            market_breadth > 0 and
            regime in ['BULL', 'HIGH_VOL']):
            
            # Calculate stop loss (below breakout level)
            atr = self._calculate_atr(candles)
            stop_loss = previous_high - atr
            target_price = current_price + (3 * atr)  # 1:3 risk-reward
            
            signal = Signal(
                symbol=symbol,
                strategy=self.name,
                signal_type=SignalType.LONG,
                entry_price=current_price,
                stop_loss=stop_loss,
                target_price=target_price,
                confidence=min(0.9, 0.5 + (volume_ratio - 2) * 0.1 + min(oi_change, 10) * 0.02),
                timeframe='5m',
                timestamp=datetime.utcnow(),
                metadata={
                    'previous_high': previous_high,
                    'volume_ratio': volume_ratio,
                    'oi_change': oi_change,
                    'market_breadth': market_breadth,
                    'regime': regime,
                    'atr': atr
                }
            )
            
            logger.info(f"BREAKOUT signal for {symbol} @ {current_price:.2f}")
            return signal
        
        return None
    
    def _calculate_atr(self, candles: pd.DataFrame, period: int = 14) -> float:
        """Calculate Average True Range"""
        high = candles['high']
        low = candles['low']
        close = candles['close'].shift(1)
        
        tr1 = high - low
        tr2 = abs(high - close)
        tr3 = abs(low - close)
        
        true_range = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = true_range.rolling(window=period).mean()
        
        return atr.iloc[-1] if not pd.isna(atr.iloc[-1]) else 0.0


# Strategy registry
STRATEGIES = {
    'ema_trend': EMATrendStrategy(),
    'vwap_mean_reversion': VWAPMeanReversionStrategy(),
    'momentum_breakout': MomentumBreakoutStrategy()
}


def get_strategy(name: str):
    """Get strategy instance by name"""
    return STRATEGIES.get(name)


def get_all_strategies() -> List[str]:
    """Get list of all available strategies"""
    return list(STRATEGIES.keys())
